services:
  db:
    image: postgres:16.3
    restart: always
    # ports: 
    #   - 5432:5432
    env_file: .env
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready"]
      interval: 3s
      timeout: 3s
      retries: 5

  app:
    image: microservice:latest
    build: .
    ports:
      - 80:8000
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
